### ISSUE TITLE
registry_key docs state incorrectly that :string is the default type

### ISSUE THREAD

**Issue by juliandunn** [chef-boneyard/chef-web-docs-2016#133]
The docs [http://docs.opscode.com/resource_registry_key.html](here) state that `:string` is the default type for registry keys, but leaving this off in recipe code doesn't work. Given recipe code:

```
registry_key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation' do
  values [{:name => 'Logo', :data => 'C:\Windows\System32\oemlogo.bmp'},
          {:name => 'Manufacturer', :data => node['windowshacks']['oeminfo']['manufacturer']},
          {:name => 'SupportHours', :data => node['windowshacks']['oeminfo']['supporthours']},
          {:name => 'SupportPhone', :data => node['windowshacks']['oeminfo']['supportphone']},
          {:name => 'SupportURL', :data => node['windowshacks']['oeminfo']['supporturl']}]
  action :create
end
```

the following stack trace is seen:

```
ArgumentError: Missing type key in RegistryKey values hash
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource/registry_key.rb:57:in `block in values'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource/registry_key.rb:55:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource/registry_key.rb:55:in `values'
c:/chef/cache/cookbooks/windowshacks/recipes/oeminfo.rb:30:in `block in from_file'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/dsl/recipe.rb:71:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/dsl/recipe.rb:71:in `method_missing'
c:/chef/cache/cookbooks/windowshacks/recipes/oeminfo.rb:25:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/cookbook_version.rb:237:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context.rb:151:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context/cookbook_compiler.rb:139:in `block in compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context/cookbook_compiler.rb:137:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context/cookbook_compiler.rb:137:in `compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context/cookbook_compiler.rb:74:in `compile'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/run_context.rb:86:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:249:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:492:in `do_run'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/client.rb:212:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/windows_service.rb:169:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/windows_service.rb:95:in `block in service_main'
<internal:prelude>:10:in `synchronize'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/windows_service.rb:75:in `service_main'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/windows_service.rb:286:in `mainloop'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/windows_service.rb:286:in `mainloop'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/windows_service.rb:286:in `<main>'
```

I'll leave it to @adamedx or @sersut to determine if the provider code should be changed to actually default to `:string` if no type is passed but in the interim the docs should be updated.

**Comment by jamescott** [comment]
I will remove "(also the default)" from the description for the value types.
