### ISSUE TITLE
Clarify chef-sync-ctl run scenarios

### ISSUE THREAD

**Issue by andrewelizondo** [chef-boneyard/chef-web-docs-2016#477]
Most of the chef-sync-ctl commands could use clarification as to where they are designed to be ran from (master/replica).

http://docs.chef.io/server_replication.html

In it's current state, several of the commands will return an obscure stack trace that make for an incredibly undelightful experience when trying to find out the failure.

e.g. running `chef-sync-ctl sync-status` on the master will produce a stack trace complaining about a missing .sock file

``` bash
$ chef-sync-ctl sync-status
(eval):8:in `initialize': No such file or directory - "/var/opt/chef-sync/ec_sync_client/ec_sync.sock" (Errno::ENOENT)
        from (eval):8:in `new'
        from (eval):8:in `block (2 levels) in load_files'
        from /opt/chef-sync/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:145:in `call'
        from /opt/chef-sync/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:145:in `block in add_command'
        from /opt/chef-sync/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:366:in `run'
        from /opt/chef-sync/embedded/bin/omnibus-addon-ctl:26:in `<main>'
```

**Comment by jamescott** [comment]
@stevendanna Hi Steven, can you help clarify which commands should run in which locations?

**Comment by stevendanna** [comment]
@jamescott all of the commands other than reconfigure and prepare-org are intended to be run on the client machine.  We should definitely beef up the error messages here too.

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/5e7623e233a3d74037eeb5c4a86553aa97717fc0

**Comment by andrewelizondo** [comment]
@jamescott the referenced commit is a good improvement, but doesn't specify that it should be run on an entirely different machine. I feel like that'll still leave quite a bit of confusion. 

Instead, how does 'This command should only be run on Chef servers acting as replicas' sound?

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/d3cda172ba1e40afec544bb9561249a7565676d4
